### PR TITLE
Add bower structure and UMD implementation

### PR DESCRIPTION
**Pull request by gh0stonio**

### CODE REVIEW

**Comment by brunowego** [comment]
+1

**Comment by gh0stonio** [comment]
Up to merge ;)

**Comment by ucay** [comment]
:+1:

**Comment by herschel666** [comment]
:+1: … though I'd like to see CommonJS-support and a `package.json` as well. ;-)

**Comment by jpetitcolas** [comment]
:+1:

**Comment by stevemao** [comment]
Any one reviewing this PR?

**Comment by bluegene37** [comment]
+1

**Comment by tholman** [comment]
Appreciate it, but not really looking to add this to any package managers. It is a joke, after all ;)

**Pull request closed without merging**
