### PR TITLE
Add bower structure, UMD implementation, gulp for min build

### PR DESCRIPTION
**Pull request by gh0stonio**

### CODE REVIEW

**Comment by stevemao** [comment]
This PR should probably be separated into several.

**Comment by gh0stonio** [comment]
How many? 
One for UMD and one for bower?

**Comment by stevemao** [comment]
Also I think jscs should probably added. There's a lot of random whitespace changes and jscs and enforce consistent coding style.

**Comment by stevemao** [comment]
@gh0stonio maybe bower, UMD and gulp?

**Comment by gh0stonio** [comment]
ok so split everything.
I close this one and create 3 PR

**Comment by stevemao** [comment]
This one could be open for bower, and create another two.

**Comment by gh0stonio** [comment]
I will make 2 PR, one for bower/umd and one for gulp i think.
I need bower to make the demo page with require so i can't split bower and umd.

**Pull request closed without merging**
