### PR TITLE
Add configurability for volume.

### PR DESCRIPTION
**Pull request by ctrezevant**
This allows users to decide just how loud the elevator music should be.

### CODE REVIEW

**Comment by angebandefu** [comment]
Can someone explain to me please? I'm really blank here.

**Comment by ctrezevant** [comment]
Essentially, when this was [posted on Reddit](
http://reddit.com/r/InternetIsBeautiful/comments/33dl7j/elevatorjs_fixes_those_awkward_scroll_to_top/),
I saw a lot of people complaining about the volume being loud.

I didn't see any configuration options for volume in elevator.js, hence the
pull request.

**Comment by tholman** [comment]
Hey man,

Thanks for doing this. Ultimately, the volume is up to the audio file... and then just how loud someone's speakers are. So going to avoid adding this little added complexity.

Appreciate the pull though, a lot!

**Comment by ctrezevant** [comment]
No problem! Love the library, by the way!

You make a great point there, especially considering that the person using the library is ultimately control of the volume anyways. 

Anyways, hope you have a great weekend!

**Comment by tholman** [comment]
Thanks! 

Yeah, volume is always a touchy thing. I like to imagine people won't abuse it too much. The demo music could have gone down a little, but that was my call :dancer: 

Cheers for understanding, too. Appreciate it!

**Pull request closed without merging**
